### ISSUE TITLE
RAM requirement for WR exclusivity test

### ISSUE THREAD

**Issue by DhanjalJK** [raphael-group/weighted-exclusivity-test#25]
I have a set of 17313 genes. On running the script for finding sets the RAM gets full very soon and the job terminates. I am working on a system with 32 GB RAM and using 10 processors. Can you please suggest something to resolve this problem? Also, I encounter the same issue if I use 10000 permutations in the previous step.

**Comment by matthewreyna** [comment]
By default, WExT evaluates all sets of a given size, which can result in a large number of sets.  For the `find_exclusive_sets.py` and `find_sets.py` scripts, please use the `-f`/`--min_frequency` argument to limit WExT to genes that meet or exceed the given mutation frequency.  For example, with `-f 10`, WExT forms gene sets from the set of genes with 10 or more mutated samples.  Please see
[examples/simple](https://github.com/raphael-group/wext/tree/master/examples/simple) for examples.

For the `compute_mutation_probabilities.py` script, please check the amount of available memory, use fewer processors, or perform fewer permutations.

**Comment by DhanjalJK** [comment]
Thanks for the reply!
