### ISSUE TITLE
Correct usage of finding_exclusive_sets.py

### ISSUE THREAD

**Issue by DhanjalJK** [raphael-group/weighted-exclusivity-test#26]
Kindly help me with the following questions-
1. Is 'python ../find_exclusive_sets.py -mf data.json -o exc -f 5 -c 20 -v 4 -s Enumerate -ks 2 -m Saddlepoint -wf weights.npy' not the correct syntax? 
2. If I want to try MCMC, how to decide the value for the required parameters (--num_iterations, --num_chains, --step_length, --alpha and --mcmc_seed)?
3. I used the value of --seed as 12345 for computing mutation probabilities after looking at the examples provided. What is the significance of this number and how to decide on its value?
Thanks!

**Comment by matthewreyna** [comment]
1. The `find_exclusive_sets.py` script allows different choices of exclusivity tests.  Please try `python ../find_exclusive_sets.py -mf data.json -o exc -f 5 -c 20 -v 4 -ks 2 -s Enumerate WRE -m Saddlepoint -wf weights.npy` to run the WR-exclusivity test from the WExT paper.  Also, if you encounter further errors, please share the error message to make it easier to provide feedback.
2. You can test these values experimentally to see if the MCMC appears to converge.  For more information about the MCMC, please see the [CoMEt paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0700-7).
3. The `-s` (`--seed`) argument for the `compute_mutation_probabilities.py` script is a seed for the random number generator used in this script.  By providing a seed, you can generate the same results when you run this script on the same data at different times.  You can choose any integer.
