### ISSUE TITLE
running time is very long

### ISSUE THREAD

**Issue by huwenhuo** [raphael-group/weighted-exclusivity-test#27]
Hi, I am running the 2nd step compute_mutation_probabilities.py for the bladder cancer mutations from TCGA. It takes for ever with 5 cores and -np 1000. The file from the 1st step is process_mutations.py is 280Mb. Any suggestion? Thanks. 

Wenhuo

**Comment by matthewreyna** [comment]
Hi Wenhuo,

Please consult our wiki page ([link](https://github.com/raphael-group/wext/wiki/Process-mutations)) for the `process_mutations.py` script to ensure that you are formatting your data correctly and calling appropriate arguments for this script.  The relatively large size of your output file suggests that there may be an issue here that could explain the long run time of the `compute_mutation_probabilities.py` script, which should complete in well under an hour depending on your data and your computer.

Please also try to run WExT on simple example data ([examples/simple](https://github.com/raphael-group/wext/tree/master/examples/simple)), which should require less than a minute.  We also have examples of running WExT on TCGA mutation data ([experiments/eccb2016](https://github.com/raphael-group/wext/tree/master/experiments/eccb2016)) that may be helpful to consult.

Best,
Matt

**Comment by huwenhuo** [comment]
Thank you very much Matt. It turns out that my maf file name was end with .maf.

**Comment by huwenhuo** [comment]
I did not install WExT in virutalenv mode, I did go through the steps suggested. 
I went through the firs two steps
process_mutations.py 
compute_mutation_probabilities.py

For the find_sets.py, I got this
Traceback (most recent call last):
  File "../../find_sets.py", line 11, in <module>
    from wext import *
ImportError: No module named wext

BTW, I also got the same error when running the example/simple/commands.sh

I guess this is a installation problem, but I don't know how to install it correctly. Any suggestion?

**Comment by matthewreyna** [comment]
Hi Wenhuo,

Virtualenv is not necessary, but the Python software libraries that it installs are necessary.  Please check that NumPy, SciPy, and NetworkX are installed.  Also, please check that you completed the setup steps in the README without errors:
```
cd wext
python setup.py build
f2py -c src/fortran/bipartite_edge_swap_module.f95 -m bipartite_edge_swap_module
```
Best,
Matt

**Comment by huwenhuo** [comment]
Thanks again Matt. 

I went around by copy the whole wext folder into the site-packages. It works. I did the build and compilation steps you mentioned. 

Have a good weekend!
