### ISSUE TITLE
Error in process_mutations step 

### ISSUE THREAD

**Issue by vermayugesh** [raphael-group/weighted-exclusivity-test#28]
Hi I am running the 1st step process_mutations.py for the BRCA mutations from TCGA After installing all the requirements for this software it is showing this error. Any suggestions? Thanks
![capture](https://user-images.githubusercontent.com/43643772/46148714-4bec8c80-c286-11e8-965f-8dcb02a02f36.PNG)

**Comment by matthewreyna** [comment]
Hello,

Please try the example in the `wext/examples/simple` folder.  If the `commands.sh` script for this example runs correctly, then please compare your data and arguments for the `process_mutations.py` script with those in this example.  From your error message, it is possible that you have unexpected (non-ASCII) characters in your data file.

Best,
Matt
